# Generated by Django 4.1 on 2024-03-02 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("campus", "0004_alter_user_group_alter_user_role_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answerarchive",
            options={
                "verbose_name": "Файл відповіді",
                "verbose_name_plural": "Файли відповіді",
            },
        ),
        migrations.AlterModelOptions(
            name="answertask",
            options={
                "verbose_name": "Відповідь на питання",
                "verbose_name_plural": "Відповіді на питання",
            },
        ),
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name": "Курс", "verbose_name_plural": "Курси"},
        ),
        migrations.AlterModelOptions(
            name="faculty",
            options={"verbose_name": "Факультет", "verbose_name_plural": "Факультети"},
        ),
        migrations.AlterModelOptions(
            name="group",
            options={"verbose_name": "Група", "verbose_name_plural": "Групи"},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={"verbose_name": "Питання", "verbose_name_plural": "Питання"},
        ),
        migrations.AlterModelOptions(
            name="specialty",
            options={
                "verbose_name": "Спеціальність",
                "verbose_name_plural": "Спеціальності",
            },
        ),
        migrations.AlterModelOptions(
            name="studentsubjectprogress",
            options={
                "verbose_name": "Успішність студента",
                "verbose_name_plural": "Успішність студентів",
            },
        ),
        migrations.AlterModelOptions(
            name="subject",
            options={"verbose_name": "Предмет", "verbose_name_plural": "Предмети"},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"verbose_name": "Завдання", "verbose_name_plural": "Завдання"},
        ),
        migrations.AlterModelOptions(
            name="test",
            options={"verbose_name": "Тест", "verbose_name_plural": "Тести"},
        ),
        migrations.AlterModelOptions(
            name="university",
            options={
                "verbose_name": "Університет",
                "verbose_name_plural": "Університети",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Користувач",
                "verbose_name_plural": "Користувачі",
            },
        ),
        migrations.RemoveField(
            model_name="question",
            name="is_correct",
        ),
        migrations.CreateModel(
            name="VariatsOfAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.CharField(max_length=255)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="campus.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Відповідь",
                "verbose_name_plural": "Відповіді",
            },
        ),
    ]
