# Generated by Django 4.1 on 2024-03-02 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0006_alter_studentsubjectprogress_num_of_pairs_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VariatsOfAnswer',
            new_name='VariantOfAnswer',
        ),
    ]
