# Generated by Django 4.1 on 2024-03-03 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campus", "0011_remove_answertask_student_answerarchive_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answerarchive",
            name="student",
        ),
    ]
